# Generated by Django 5.2.13 on 2026-04-27 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ik', '0005_remove_profile_city_profile_avatar_profile_bio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Uncheck to hide this announcement'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='link',
            field=models.URLField(blank=True, help_text='Optional link (e.g., /deals/ or /contact/)', null=True),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Lower numbers appear first'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='text',
            field=models.CharField(help_text="Announcement text (e.g., 'Free Delivery on orders above Rs. 2000')", max_length=300),
        ),
    ]
