# Generated by Django 5.2.13 on 2026-04-27 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ik', '0006_alter_announcement_is_active_alter_announcement_link_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomepageSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sweet_creations_title', models.CharField(default='Our Sweet <em>Creations</em>', help_text='HTML allowed (e.g., <em>Creations</em>)', max_length=200)),
                ('sweet_creations_subtitle', models.CharField(default='Explore our wide range of delicious cakes and pastries — click to discover more!', help_text='Plain text or HTML', max_length=300)),
                ('show_section', models.BooleanField(default=True, help_text='Uncheck to hide the entire Sweet Creations section')),
            ],
            options={
                'verbose_name': 'Homepage Setting',
                'verbose_name_plural': 'Homepage Settings',
            },
        ),
    ]
