# Generated by Django 5.2.13 on 2026-04-29 01:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ik', '0008_eventchatsession'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BakingInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed', models.BooleanField(default=False)),
                ('answers', models.JSONField(default=dict)),
                ('reference_image', models.ImageField(blank=True, null=True, upload_to='inquiry_images/')),
                ('chosen_package', models.CharField(blank=True, max_length=50, null=True)),
                ('total_estimated_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Baking Inquiry',
                'verbose_name_plural': 'Baking Inquiries',
                'ordering': ['-created_at'],
            },
        ),
    ]
