# Generated by Django 5.2.13 on 2026-05-06 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ik', '0016_profile_default_delivery_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
