# Generated by Django 5.2.13 on 2026-05-07 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ik', '0017_product_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bakinginquiry',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='eventchatsession',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='announcement',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='text',
            field=models.CharField(help_text='Announcement text', max_length=300),
        ),
        migrations.AlterField(
            model_name='eventorder',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='eventpackage',
            name='includes_extras',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='homepagesettings',
            name='show_section',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='homepagesettings',
            name='sweet_creations_subtitle',
            field=models.CharField(default='Explore our wide range of delicious cakes and pastries — click to discover more!', max_length=300),
        ),
        migrations.AlterField(
            model_name='homepagesettings',
            name='sweet_creations_title',
            field=models.CharField(default='Our Sweet <em>Creations</em>', help_text='HTML allowed', max_length=200),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
