# Generated by Django 5.2.13 on 2026-05-13 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ik', '0019_alter_whatsappnumber_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bakery_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('logo', models.ImageField(blank=True, null=True, upload_to='settings/')),
                ('facebook', models.URLField(blank=True)),
                ('instagram', models.URLField(blank=True)),
                ('whatsapp', models.URLField(blank=True)),
                ('youtube', models.URLField(blank=True)),
                ('whatsapp_number', models.CharField(blank=True, max_length=20)),
                ('whatsapp_message', models.TextField(blank=True)),
                ('dark_mode', models.BooleanField(default=False)),
                ('primary_color', models.CharField(default='#ff4081', max_length=20)),
                ('username', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
