# Generated by Django 5.2.13 on 2026-05-13 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ik', '0020_sitesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='admin_logo',
            field=models.ImageField(blank=True, help_text='Admin panel logo (optional)', null=True, upload_to='settings/'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='footer_logo',
            field=models.ImageField(blank=True, help_text='Footer logo (optional, uses main logo if empty)', null=True, upload_to='settings/'),
        ),
    ]
