# Generated by Django 5.2.13 on 2026-05-14 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ik', '0022_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='discount_percentage',
            field=models.IntegerField(default=0),
        ),
    ]
