# Generated by Django 5.2.13 on 2026-05-15 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ik', '0024_alter_deal_options_remove_deal_deal_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', help_text='Message priority level', max_length=20),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='subject',
            field=models.CharField(blank=True, help_text='Message subject', max_length=200),
        ),
        migrations.AddField(
            model_name='eventbooking',
            name='event_date',
            field=models.DateField(blank=True, help_text='Date of the event', null=True),
        ),
        migrations.AddField(
            model_name='eventbooking',
            name='event_image',
            field=models.ImageField(blank=True, help_text='Event reference image', null=True, upload_to='events/'),
        ),
        migrations.AddField(
            model_name='eventbooking',
            name='event_time',
            field=models.TimeField(blank=True, help_text='Time of the event', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='city',
            field=models.CharField(blank=True, help_text='Customer city', max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='order_type',
            field=models.CharField(choices=[('normal', 'Normal'), ('custom', 'Custom'), ('event', 'Event')], default='normal', help_text='Type of order', max_length=30),
        ),
        migrations.AddField(
            model_name='order',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Last updated timestamp'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Show on homepage featured section'),
        ),
        migrations.AddField(
            model_name='product',
            name='stock',
            field=models.PositiveIntegerField(default=0, help_text='Available stock quantity'),
        ),
    ]
