# Generated by Django 5.2.13 on 2026-05-17 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ik', '0025_contactmessage_priority_contactmessage_subject_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='advance_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='remaining_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
