# Generated by Django 5.2.13 on 2026-05-17 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ik', '0026_order_advance_amount_order_remaining_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Partial Paid', 'Partial Paid'), ('Fully Paid', 'Fully Paid'), ('Failed', 'Failed')], default='Pending', max_length=20),
        ),
    ]
