# Generated by Django 5.2.13 on 2026-05-19 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ik', '0028_order_ip_address_order_is_payment_flagged_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('cake', 'Cake'), ('cookie', 'Cookie'), ('brownie', 'Brownie')], default='cake', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('under_review', 'Under Review'), ('partial_paid', 'Partial Paid'), ('fully_paid', 'Fully Paid'), ('rejected', 'Rejected')], default='under_review', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_verified',
            field=models.BooleanField(default=True),
        ),
    ]
