# Generated by Django 5.2.13 on 2026-05-19 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ik', '0029_product_product_type_alter_order_payment_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_type',
            field=models.CharField(choices=[('website', 'Website'), ('custom', 'Custom'), ('deal', 'Deal'), ('event', 'Event'), ('whatsapp', 'WhatsApp')], default='website', help_text='Source of order', max_length=30),
        ),
    ]
