# Generated by Django 5.2.13 on 2026-05-22 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ik', '0032_alter_order_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='screenshot_hash',
            field=models.CharField(blank=True, db_index=True, help_text='Unique hash for payment screenshot', max_length=64, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='admin_logo',
            field=models.ImageField(blank=True, null=True, upload_to='settings/'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='footer_logo',
            field=models.ImageField(blank=True, null=True, upload_to='settings/'),
        ),
        migrations.AlterField(
            model_name='whatsappnumber',
            name='customer_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='whatsappnumber',
            name='event_booking_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='whatsappnumber',
            name='follow_up_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='whatsappnumber',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='whatsappnumber',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='whatsappnumber',
            name='order_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='whatsappnumber',
            name='product_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
