# Generated by Django 5.2.13 on 2026-05-24 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ik', '0036_alter_order_payment_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='received_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Actual amount received from customer', max_digits=10),
        ),
    ]
