# Generated by Django 5.2.13 on 2026-05-28 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ik', '0037_order_received_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventbooking',
            name='pickup_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventbooking',
            name='relation_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('cake', 'Cake'), ('cookie', 'Cookie'), ('brownie', 'Brownie'), ('bento', 'Bento')], default='cake', max_length=20),
        ),
    ]
