# Generated by Django 5.2.13 on 2026-05-29 11:43

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ik', '0038_eventbooking_pickup_time_eventbooking_relation_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventinquiry',
            name='notes',
            field=models.TextField(blank=True, help_text='Internal notes for admin'),
        ),
        migrations.AddField(
            model_name='eventinquiry',
            name='planner_answers',
            field=models.JSONField(blank=True, default=dict, help_text='Stores all step‑by‑step answers from the smart planner'),
        ),
        migrations.AddField(
            model_name='eventinquiry',
            name='reference_image',
            field=models.ImageField(blank=True, help_text='Customer uploaded reference image', null=True, upload_to='event_inquiries/'),
        ),
        migrations.AddField(
            model_name='eventinquiry',
            name='selected_package',
            field=models.ForeignKey(blank=True, help_text='Package selected by customer or admin', null=True, on_delete=django.db.models.deletion.SET_NULL, to='ik.eventpackage'),
        ),
        migrations.AddField(
            model_name='eventpackage',
            name='display_order',
            field=models.PositiveIntegerField(default=0, help_text='Order in which packages appear'),
        ),
        migrations.AddField(
            model_name='eventpackage',
            name='image',
            field=models.ImageField(blank=True, help_text='Package image/thumbnail', null=True, upload_to='event_packages/'),
        ),
        migrations.AddField(
            model_name='eventpackage',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Feature on homepage'),
        ),
        migrations.AddField(
            model_name='eventpackage',
            name='max_budget',
            field=models.PositiveIntegerField(default=1000000, help_text='Maximum budget for this package'),
        ),
        migrations.AddField(
            model_name='eventpackage',
            name='max_guests',
            field=models.PositiveIntegerField(default=1000, help_text='Maximum number of guests'),
        ),
        migrations.AddField(
            model_name='eventpackage',
            name='min_budget',
            field=models.PositiveIntegerField(default=0, help_text='Minimum budget for this package'),
        ),
        migrations.AddField(
            model_name='eventpackage',
            name='min_guests',
            field=models.PositiveIntegerField(default=1, help_text='Minimum number of guests'),
        ),
        migrations.AddField(
            model_name='eventpackage',
            name='recommended',
            field=models.BooleanField(default=False, help_text='Show as recommended package'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='tiktok',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='eventinquiry',
            name='phone',
            field=models.CharField(help_text='Enter Pakistani number like 03XXXXXXXXX', max_length=20, validators=[django.core.validators.RegexValidator(message='Phone number must be in format 03XXXXXXXXX', regex='^03\\d{9}$')]),
        ),
    ]
