# Generated by Django 5.2.13 on 2026-04-25 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ik', '0002_contactmessage_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(help_text="Announcement text (e.g., 'Free Delivery on orders above Rs. 2000')", max_length=300)),
                ('link', models.URLField(blank=True, help_text='Optional link (e.g., /deals/ or /contact/)', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to hide this announcement')),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Announcement',
                'verbose_name_plural': 'Announcements',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
