# Generated by Django 5.2.13 on 2026-04-29 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ik', '0009_bakinginquiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='bakinginquiry',
            name='order_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bakinginquiry',
            name='payment_status',
            field=models.CharField(default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='bakinginquiry',
            name='selected_deal',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bakinginquiry',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
