# Generated by Django 5.2.13 on 2026-05-02 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ik', '0012_profile_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('event_type', models.CharField(choices=[('Birthday', 'Birthday'), ('Wedding', 'Wedding'), ('Anniversary', 'Anniversary'), ('Baby Shower', 'Baby Shower'), ('Graduation', 'Graduation'), ('Corporate', 'Corporate')], max_length=50)),
                ('guests', models.IntegerField(default=25)),
                ('budget', models.IntegerField(default=5000)),
                ('cake_size', models.CharField(blank=True, max_length=50)),
                ('cake_flavor', models.CharField(blank=True, max_length=100)),
                ('extras', models.TextField(blank=True)),
                ('selected_deal', models.CharField(blank=True, max_length=255)),
                ('deal_items', models.JSONField(blank=True, default=list)),
                ('planner_answers', models.JSONField(blank=True, default=dict)),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Preparing', 'Preparing'), ('Delivered', 'Delivered')], default='Pending', max_length=20)),
                ('whatsapp_sent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='EventRequest',
        ),
    ]
