# Generated by Django 5.2.13 on 2026-05-03 06:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ik', '0013_eventbooking_delete_eventrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(max_length=20)),
                ('event_type', models.CharField(blank=True, choices=[('birthday', 'Birthday'), ('wedding', 'Wedding'), ('anniversary', 'Anniversary'), ('baby_shower', 'Baby Shower'), ('graduation', 'Graduation'), ('corporate', 'Corporate')], max_length=50)),
                ('guests', models.IntegerField(default=25)),
                ('budget', models.IntegerField(default=5000)),
                ('preferred_date', models.DateField(blank=True, null=True)),
                ('message', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('converted', 'Converted'), ('lost', 'Lost')], default='new', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='EventPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('event_type', models.CharField(choices=[('birthday', 'Birthday'), ('wedding', 'Wedding'), ('anniversary', 'Anniversary'), ('baby_shower', 'Baby Shower'), ('graduation', 'Graduation'), ('corporate', 'Corporate')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cake_size', models.CharField(blank=True, max_length=50)),
                ('cake_flavor', models.CharField(blank=True, max_length=50)),
                ('includes_extras', models.TextField(blank=True, help_text='Comma-separated list')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='EventOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(blank=True, max_length=20, unique=True)),
                ('customer_name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('event_date', models.DateField()),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('advance_paid', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('remaining', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('preparing', 'Preparing'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('payment_status', models.CharField(choices=[('unpaid', 'Unpaid'), ('partial', 'Partial'), ('paid', 'Paid')], default='unpaid', max_length=20)),
                ('transaction_id', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('inquiry', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ik.eventinquiry')),
                ('package', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ik.eventpackage')),
            ],
        ),
    ]
