# Generated by Django 5.2.13 on 2026-05-03 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ik', '0014_eventinquiry_eventpackage_eventorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='invoice_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
