# Generated by Django 5.2.13 on 2026-05-04 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ik', '0015_order_invoice_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='default_delivery_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='delivery_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='phone_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='whatsapp_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
