# Generated by Django 5.2.13 on 2026-05-11 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ik', '0018_alter_bakinginquiry_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='whatsappnumber',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='whatsappnumber',
            name='customer_name',
            field=models.CharField(blank=True, help_text='Customer full name', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='whatsappnumber',
            name='event_booking_id',
            field=models.IntegerField(blank=True, help_text='Related Event Booking ID', null=True),
        ),
        migrations.AddField(
            model_name='whatsappnumber',
            name='follow_up_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='whatsappnumber',
            name='follow_up_date',
            field=models.DateTimeField(blank=True, help_text='Next follow-up date', null=True),
        ),
        migrations.AddField(
            model_name='whatsappnumber',
            name='last_contacted',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='whatsappnumber',
            name='lead_source',
            field=models.CharField(choices=[('website', 'Website Order'), ('contact_form', 'Contact Form'), ('chat', 'Live Chat'), ('event_planner', 'Event Planner'), ('baking_assistant', 'Baking Assistant'), ('manual', 'Manual Entry'), ('whatsapp', 'WhatsApp Direct')], default='manual', max_length=20),
        ),
        migrations.AddField(
            model_name='whatsappnumber',
            name='message',
            field=models.TextField(blank=True, help_text='Original WhatsApp message or inquiry', null=True),
        ),
        migrations.AddField(
            model_name='whatsappnumber',
            name='notes',
            field=models.TextField(blank=True, help_text='Internal notes for sales team', null=True),
        ),
        migrations.AddField(
            model_name='whatsappnumber',
            name='order_id',
            field=models.IntegerField(blank=True, help_text='Related Order ID if converted', null=True),
        ),
        migrations.AddField(
            model_name='whatsappnumber',
            name='product_name',
            field=models.CharField(blank=True, help_text='Product they inquired about', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='whatsappnumber',
            name='status',
            field=models.CharField(choices=[('new', 'New Lead'), ('contacted', 'Contacted'), ('followup', 'Follow-up Required'), ('negotiation', 'Negotiation'), ('converted', 'Converted to Order'), ('lost', 'Lost'), ('cancelled', 'Cancelled')], default='new', max_length=20),
        ),
        migrations.AddField(
            model_name='whatsappnumber',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
