# Generated by Django 5.2.13 on 2026-05-13 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ik', '0021_sitesettings_admin_logo_sitesettings_footer_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='categories/'),
        ),
    ]
