# Generated by Django 5.2.13 on 2026-05-14 12:15

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ik', '0023_deal_discount_percentage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deal',
            options={'ordering': ['sort_order', '-created_at'], 'verbose_name': 'Deal', 'verbose_name_plural': 'Deals'},
        ),
        migrations.RemoveField(
            model_name='deal',
            name='deal_price',
        ),
        migrations.RemoveField(
            model_name='deal',
            name='discount_percentage',
        ),
        migrations.RemoveField(
            model_name='deal',
            name='original_price',
        ),
        migrations.AddField(
            model_name='deal',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='deal',
            name='expiry',
            field=models.DateTimeField(blank=True, help_text='Deal expiration date/time', null=True),
        ),
        migrations.AlterField(
            model_name='deal',
            name='image',
            field=models.ImageField(help_text='Deal promotional image', upload_to='deals/'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Show this deal on website'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='product',
            field=models.ForeignKey(blank=True, help_text='Optional: Link to a product', null=True, on_delete=django.db.models.deletion.SET_NULL, to='ik.product'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='sort_order',
            field=models.PositiveIntegerField(default=0, help_text='Lower numbers appear first'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='subtitle',
            field=models.CharField(blank=True, help_text='Short description for the deal', max_length=300),
        ),
        migrations.AlterField(
            model_name='deal',
            name='title',
            field=models.CharField(help_text="Deal title (e.g., 'Eid Special Deal')", max_length=200),
        ),
    ]
