# Generated by Django 5.2.13 on 2026-05-18 01:07

import ik.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ik', '0027_alter_order_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='is_payment_flagged',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_screenshot',
            field=models.ImageField(blank=True, help_text='Payment screenshot proof', null=True, upload_to='payments/', validators=[ik.models.validate_payment_screenshot]),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='suspicious_attempts',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='transaction_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='user_agent',
            field=models.TextField(blank=True, help_text='Browser/Device info', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='verification_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('jazzcash', 'JazzCash'), ('easypaisa', 'EasyPaisa')], max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('under_review', 'Under Review'), ('verified', 'Verified'), ('rejected', 'Rejected'), ('failed', 'Failed')], default='under_review', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='transaction_id',
            field=models.CharField(blank=True, db_index=True, help_text='Unique JazzCash/EasyPaisa transaction ID', max_length=50, null=True, unique=True),
        ),
    ]
