# Generated by Django 5.2.13 on 2026-05-19 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ik', '0030_alter_order_order_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_verified',
            field=models.BooleanField(default=False),
        ),
    ]
