# Generated by Django 5.2.13 on 2026-05-21 13:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ik', '0031_alter_order_payment_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.CharField(help_text='Enter Pakistani number like 03XXXXXXXXX', max_length=20, validators=[django.core.validators.RegexValidator(message='Phone number must be in format 03XXXXXXXXX', regex='^03\\d{9}$')]),
        ),
    ]
