# Generated by Django 5.2.13 on 2026-05-23 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ik', '0033_order_screenshot_hash_alter_sitesettings_admin_logo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='easypaisa_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='jazzcash_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
