# Generated by Django 5.2.13 on 2026-05-23 09:07

import ik.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ik', '0034_sitesettings_easypaisa_number_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='remaining_payment_screenshot',
            field=models.ImageField(blank=True, help_text='Screenshot for remaining payment', null=True, upload_to='remaining_payments/', validators=[ik.models.validate_payment_screenshot]),
        ),
        migrations.AddField(
            model_name='order',
            name='remaining_payment_verified',
            field=models.BooleanField(default=False, help_text='Whether remaining payment has been verified by admin'),
        ),
        migrations.AddField(
            model_name='order',
            name='remaining_screenshot_hash',
            field=models.CharField(blank=True, db_index=True, help_text='Hash for remaining payment screenshot', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='remaining_transaction_id',
            field=models.CharField(blank=True, db_index=True, help_text='Transaction ID for remaining payment', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='whatsappnumber',
            name='advance_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Advance payment received', max_digits=10),
        ),
        migrations.AddField(
            model_name='whatsappnumber',
            name='payment_verified',
            field=models.BooleanField(default=False, help_text='Whether payment has been verified by admin'),
        ),
        migrations.AddField(
            model_name='whatsappnumber',
            name='remaining_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Remaining payment amount', max_digits=10),
        ),
        migrations.AddField(
            model_name='whatsappnumber',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total order amount', max_digits=10),
        ),
        migrations.AddField(
            model_name='whatsappnumber',
            name='transaction_id',
            field=models.CharField(blank=True, help_text='Transaction ID for the payment', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='whatsappnumber',
            name='status',
            field=models.CharField(choices=[('lead', 'New Lead'), ('followup', 'Follow Up'), ('working', 'Working'), ('converted', 'Converted'), ('rejected', 'Rejected')], db_index=True, default='lead', help_text='Lead status in CRM pipeline', max_length=20),
        ),
        migrations.AddIndex(
            model_name='whatsappnumber',
            index=models.Index(fields=['status'], name='ik_whatsapp_status_063c99_idx'),
        ),
        migrations.AddIndex(
            model_name='whatsappnumber',
            index=models.Index(fields=['phone_number'], name='ik_whatsapp_phone_n_73fb0a_idx'),
        ),
        migrations.AddIndex(
            model_name='whatsappnumber',
            index=models.Index(fields=['created_at'], name='ik_whatsapp_created_93bfae_idx'),
        ),
        migrations.AddIndex(
            model_name='whatsappnumber',
            index=models.Index(fields=['payment_verified'], name='ik_whatsapp_payment_0ad23a_idx'),
        ),
        migrations.AddIndex(
            model_name='whatsappnumber',
            index=models.Index(fields=['lead_source'], name='ik_whatsapp_lead_so_51d835_idx'),
        ),
    ]
