# Generated by Django 5.2.13 on 2026-05-23 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ik', '0035_order_remaining_payment_screenshot_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('jazzcash', 'JazzCash'), ('easypaisa', 'EasyPaisa'), ('cod', 'Cash on Delivery')], max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='transaction_id',
            field=models.CharField(blank=True, db_index=True, help_text='Unique JazzCash/EasyPaisa transaction ID', max_length=50, null=True),
        ),
    ]
