# Generated by Django 5.2.13 on 2026-05-31 12:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ik', '0039_eventinquiry_notes_eventinquiry_planner_answers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventbooking',
            name='advance_payment',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Advance payment received', max_digits=10),
        ),
        migrations.AddField(
            model_name='eventbooking',
            name='delivery_type',
            field=models.CharField(blank=True, default='Pickup', help_text='Pickup or Delivery', max_length=50),
        ),
        migrations.AddField(
            model_name='eventbooking',
            name='order_summary',
            field=models.JSONField(blank=True, default=dict, help_text='Full order details (items, prices, etc.)'),
        ),
        migrations.AddField(
            model_name='eventbooking',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('partial_paid', 'Partial Paid'), ('fully_paid', 'Fully Paid'), ('rejected', 'Rejected')], default='pending', help_text='Payment status', max_length=30),
        ),
        migrations.AddField(
            model_name='eventbooking',
            name='payment_verified',
            field=models.BooleanField(default=False, help_text='Admin verified payment'),
        ),
        migrations.AddField(
            model_name='eventbooking',
            name='remaining_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Remaining amount after advance', max_digits=10),
        ),
        migrations.AddField(
            model_name='eventbooking',
            name='selected_package',
            field=models.CharField(blank=True, help_text='Selected package name (Silver/Gold/Premium)', max_length=255),
        ),
        migrations.AddField(
            model_name='eventbooking',
            name='special_instructions',
            field=models.TextField(blank=True, help_text='Any special requests'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='text',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=20),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='subject',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='deal',
            name='expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='deal',
            name='image',
            field=models.ImageField(upload_to='deals/'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='deal',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ik.product'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='sort_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='deal',
            name='subtitle',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='deal',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='eventinquiry',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='eventinquiry',
            name='planner_answers',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='eventinquiry',
            name='reference_image',
            field=models.ImageField(blank=True, null=True, upload_to='event_inquiries/'),
        ),
        migrations.AlterField(
            model_name='eventinquiry',
            name='selected_package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ik.eventpackage'),
        ),
        migrations.AlterField(
            model_name='eventpackage',
            name='display_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='eventpackage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='event_packages/'),
        ),
        migrations.AlterField(
            model_name='eventpackage',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='eventpackage',
            name='max_budget',
            field=models.PositiveIntegerField(default=1000000, help_text='Maximum budget'),
        ),
        migrations.AlterField(
            model_name='eventpackage',
            name='max_guests',
            field=models.PositiveIntegerField(default=1000),
        ),
        migrations.AlterField(
            model_name='eventpackage',
            name='min_budget',
            field=models.PositiveIntegerField(default=0, help_text='Minimum budget'),
        ),
        migrations.AlterField(
            model_name='eventpackage',
            name='min_guests',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='eventpackage',
            name='recommended',
            field=models.BooleanField(default=False),
        ),
    ]
